# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setup_font()
        self.stoper()
        self.start_stop()
        self.calendar()
        self.statistic()
        self.goal_setup()
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuGoal_setup = QtWidgets.QMenu(self.menubar)
        self.menuGoal_setup.setObjectName("menuGoal_setup")
        self.menuStat = QtWidgets.QMenu(self.menubar)
        self.menuStat.setObjectName("menuStat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuGoal_setup.menuAction())
        self.menubar.addAction(self.menuStat.menuAction())


        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setup_font(self):
        self.font = QtGui.QFont()
        self.font.setFamily("Constantia")
        self.font.setPointSize(18)

    def stoper(self):
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(120, 60, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(48)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.stoper_check_box()

    def stoper_check_box(self):
        self.check_box = QtWidgets.QLabel(self.centralwidget)
        self.check_box.setGeometry(QtCore.QRect(120, 150, 151, 41))
        self.check_box.setObjectName("check_box")

    def start_stop(self):
        self.start_stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_stop_button.setGeometry(QtCore.QRect(150, 230, 101, 41))
        self.start_stop_button.setFont(self.font)
        self.start_stop_button.setObjectName("start_stop_button")

    def statistic(self):
        self.stat_button = QtWidgets.QPushButton(self.centralwidget)
        self.stat_button.setGeometry(QtCore.QRect(400, 430, 121, 51))
        self.stat_button.setFont(self.font)
        self.stat_button.setObjectName("stat_button")

    def calendar(self):
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 310, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")

    def goal_setup(self):
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 100, 111, 31))
        self.label.setFont(self.font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.defined_goal()

    def defined_goal(self):
        self.goal_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.goal_1.setGeometry(QtCore.QRect(390, 140, 101, 17))
        self.font.setPointSize(10)
        self.goal_1.setFont(self.font)
        self.goal_1.setObjectName("goal_1")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time.setText(_translate("MainWindow", "20:00"))
        self.start_stop_button.setText(_translate("MainWindow", "Start"))
        self.stat_button.setText(_translate("MainWindow", "Stat"))
        self.check_box.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Goal:"))
        self.goal_1.setText(_translate("MainWindow", "CheckBox"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuGoal_setup.setTitle(_translate("MainWindow", "Goal - setup"))
        self.menuStat.setTitle(_translate("MainWindow", "Stat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
